# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: github follower - following compare

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: load resources
      uses: actions/checkout@v4
    - name: Install cjk font
      run: sudo apt-get install fonts-noto-cjk
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: do main task
      env:
        GithubAPIKey: ${{ secrets.GithubAPIKey }}
        senderEmail: ${{ secrets.senderEmail }}
        senderTempPwd: ${{ secrets.senderTempPwd }}
        ToEmail: ${{ secrets.ToEmail }}
      run: |
        dotnet /home/runner/work/githubFollowCompare/githubFollowCompare/bin/Release/net8.0/githubFollowCompare.dll collect --targetAccount wasd52030
        dotnet /home/runner/work/githubFollowCompare/githubFollowCompare/bin/Release/net8.0/githubFollowCompare.dll collect --targetAccount lurwx52030
